[package]
name = "hash-db"
version = "0.11.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Trait for hash-keyed databases."
license = "Apache-2.0"
categories = [ "no-std" ]

[features]
default = ["std"]
std = []
